FROM digrouz/alpine-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG SONARR_VERSION='4.0.14.2939'
ARG SONARR_BRANCH='main'
ARG SONARR_ARCH='x64'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    XDG_CONFIG_HOME='/config/xdg' \
    SONARR_VERSION="${SONARR_VERSION}" \
    SONARR_BRANCH="${SONARR_BRANCH}" \
    SONARR_ARCH="${SONARR_ARCH}"
    
### Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      ca-certificates \
      curl \
    && \
    apk add --no-cache --virtual=run-deps \
      icu-libs \
      sqlite-libs \
      mediainfo \
      unzip \
      xmlstarlet \
    && \
    curl -SsL "https://github.com/Sonarr/Sonarr/releases/download/v${SONARR_VERSION}/Sonarr.${SONARR_BRANCH}.${SONARR_VERSION}.linux-musl-${SONARR_ARCH}.tar.gz" -o /tmp/sonarr.tar.gz && \
    tar xzf /tmp/sonarr.tar.gz -C /opt && \
    echo "export XDG_CONFIG_HOME='${XDG_CONFIG_HOME}'" >> /etc/profile.d/docker-xdg.sh && \
    chmod 0755 /opt/Sonarr && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*
    
### Volume
Volume ["/config"]

### Expose ports
Expose 8989
