FROM alpine:3.11
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG RADARR_VERSION="0.2.0.1480"

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='radarr' \
    APPUID='10033' \
    APPGID='10033' \
    XDG_CONFIG_HOME='/config/xdg' \
    RADARR_VERSION="${RADARR_VERSION}"
    
### Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER="${APPUSER}" && \
    MYUID="${APPUID}" && \
    MYGID="${APPGID}" && \
    ConfigureUser && \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      ca-certificates \
      curl \
      jq \
    && \
    apk add --no-cache --virtual=run-deps \
      bash \
      mediainfo \
      su-exec \
      unrar \
      unzip \
    && \
    apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/testing --virtual=run-deps-testing \
      mono \
    && \
    mozroots --import --sync && \
    cert-sync /etc/ssl/certs/ca-certificates.crt && \
    ln -s /usr/lib/libmono-native.so.0 /usr/lib/libmono-native.so && \
    curl -SsL https://github.com/Radarr/Radarr/releases/download/v${RADARR_VERSION}/Radarr.develop.${RADARR_VERSION}.linux.tar.gz -o /tmp/radarr.tar.gz && \
    tar xzf /tmp/radarr.tar.gz -C /opt && \
    echo "export XDG_CONFIG_HOME='${XDG_CONFIG_HOME}'" >> /etc/profile.d/docker-xdg.sh && \
    chmod 0755 /opt/Radarr && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    mkdir /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*
    
### Volume
Volume ["/config"]

### Expose ports
Expose 7878

### Running User: not used, managed by docker-entrypoint.sh
#USER radarr

### Start radarr
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["radarr"]
