FROM digrouz/alpine-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG SONARR_VERSION='3.0.9.1549'
ARG SONARR_BRANCH='main'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    XDG_CONFIG_HOME='/config/xdg' \
    SONARR_VERSION="${SONARR_VERSION}" \
    SONARR_BRANCH="${SONARR_BRANCH}"
    
### Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER="${APPUSER}" && \
    MYUID="${APPUID}" && \
    MYGID="${APPGID}" && \
    ConfigureUser && \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      ca-certificates \
      curl \
    && \
    apk add --no-cache --virtual=run-deps \
      mediainfo \
      unzip \
    && \
    apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/testing --virtual=run-deps-testing \
      mono \
    && \
    cert-sync /etc/ssl/certs/ca-certificates.crt && \
    curl -SsL "https://download.sonarr.tv/v3/${SONARR_BRANCH}/${SONARR_VERSION}/Sonarr.${SONARR_BRANCH}.${SONARR_VERSION}.linux.tar.gz" -o /tmp/sonarr.tar.gz && \
    tar xzf /tmp/sonarr.tar.gz -C /opt && \
    echo "export XDG_CONFIG_HOME='${XDG_CONFIG_HOME}'" >> /etc/profile.d/docker-xdg.sh && \
    chmod 0755 /opt/Sonarr && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*
    
### Volume
Volume ["/config"]

### Expose ports
Expose 8989
